- hosts: localhost
  gather_facts: no
  vars_files:
    - keys.yml
  tasks:
    - name: Attach Volume
      ec2_vol:
        aws_access_key: "{{AWS_ACCESS_KEY_ID}}"
        aws_secret_key: "{{AWS_SECRET_ACCESS_KEY}}"
        ec2_region: "{{AWS_REGION}}"
        instance: i-0b1804e988c07b743
        id: vol-06b88d48234357eb9
        delete_on_termination: yes
      register: vol_info
    - debug:
        var: vol_info      