- hosts: localhost
  gather_facts: no
  vars_files:
    - keys.yml
  tasks:
    - name: Create new AMI
      ec2_ami:
        aws_access_key: "{{AWS_ACCESSS_KEY_ID}}"
        aws_secret_key: "{{AWS_SECRET_ACCESS_KEY}}"
        ec2_region: "{{AWS_REGION}}"
        instance_id: i-006acf995e3cb3999
        name: MyNewAMI
        wait: yes
        state: present
