- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Add string to AWS Secrets Manager
      aws_secret:
        name: 'varOne'
        state: present
        secret_type: 'string'
        secret: "{\"varOne\":\"I love DevOps\"}"
      register: secret_facts
    - debug:
        var: secret_facts