- hosts: localhost
  gather_facts: no
  vars_files:
    - keys.yml
  tasks:
    - name: Create new VPC
      ec2_vpc_net:
        aws_access_key: "{{AWS_ACCESSS_KEY_ID}}"
        aws_secret_key: "{{AWS_SECRET_ACCESS_KEY}}"
        ec2_region: "{{AWS_REGION}}"
        name: newVPC
        cidr_bock: 10.10.0.0/16
        tags:
          client: test
        tenancy: dedicated
